{% set name = "google-cloud-automl" %}
{% set version = "2.0.0" %}
{% set sha256 = "fbf1c51b1441ee596d5a7d154c8c2c9b25780698d3bc9e02f4e48773440c199a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev
    - enum34

test:
  imports:
    - grpc
    - google.cloud.automl
    - google.cloud.automl_v1
    - google.cloud.automl_v1beta1

about:
  home: https://github.com/googleapis/python-automl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud AutoML API client library
  description: "Google Cloud AutoML API is a suite of machine learning products that enables developers with limited machine learning expertise to train high-quality models specific to their business needs, by leveraging Google’s state-of-the-art transfer learning, and Neural Architecture Search technology.\nSee the [quick\
    \ start guide](https://googleapis.dev/python/automl/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/automl/latest/index.html
  dev_url: https://github.com/googleapis/python-automl

extra:
  recipe-maintainers:
    - parthea
